### ISSUE TITLE
libzlib package does not contain file *.a but the test exist 

### ISSUE THREAD

**Issue by ekomarova** [conda-forge/zlib-feedstock#71]
### Comment:

libzlib test for osx (the same for linux) involve checking the existence of library *.a, which are not in the source package, which makes the test fails:
```
test ! -f ${PREFIX}/lib/libz.a
```
https://github.com/conda-forge/zlib-feedstock/blob/main/recipe/meta.yaml#L47
The contents of lib directory shows that no such files exist:
```
ls pkgs/libzlib-1.2.13-hfd90126_4/lib/
libz.1.2.13.dylib       libz.1.dylib
```

**Comment by isuruf** [comment]
The test is checking that the file does not exist.

**Comment by ekomarova** [comment]
Oops, sorry, my mistake.

**Comment by ekomarova** [comment]
The problem arose because my conda env also had zlib installed, which has libz.a
