### ISSUE TITLE
Is it on purpose that `libz.dylib` is in the `zlib` package?

### ISSUE THREAD

**Issue by wolfv** [conda-forge/zlib-feedstock#81]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The package gets split, but `libz.dylib / so` is added to the `zlib` package and not the `libzlib` package.

Only 

```
- lib/libz.1.3.1.dylib
- lib/libz.1.dylib
```

are in the `libzlib` package.

Just wondering if that's on purpose or not :)

### Installed packages

```shell
/
```

### Environment info

```shell
/
```

**Comment by isuruf** [comment]
Yes, it is on purpose. `zlib` package is for development like `libz-devel` in centos and `libz-dev` in ubuntu.

**Comment by wolfv** [comment]
Thanks, didn't know that that's how they are supposed to be split up. Good to learn :)
